In [27]:
import psycopg2

conn = psycopg2.connect(dbname="anyway", user="anyway", password="anyway", host="db")
cur = conn.cursor()

In [28]:
query = "SELECT * FROM markers ORDER BY created ASC LIMIT 1000"
cur.execute(query)
markers = cur.fetchall()

In [29]:
column_names = [desc[0] for desc in cur.description]
for column in column_names:
    print(column)

id
latitude
longitude
type
title
created
provider_code
description
address
mainStreet
secondaryStreet
junction
one_lane
multi_lane
speed_limit
road_width
road_sign
road_light
road_control
weather
road_surface
road_object
object_distance
didnt_cross
cross_mode
cross_location
cross_direction
video_link
km
road1
road2
day_in_week
day_night
district
geo_area
natural_area
region
traffic_light
yishuv_shape
yishuv_symbol
geom
accident_day
accident_hour
accident_hour_raw
accident_minute
accident_month
accident_year
non_urban_intersection
provider_and_id
street1
street2
urban_intersection
accident_severity
accident_type
day_type
location_accuracy
non_urban_intersection_hebrew
police_unit
road_intactness
road_shape
road_type
street1_hebrew
street2_hebrew
yishuv_name
x
y
municipal_status
vehicle_type_rsa
violation_type_rsa
house_number
file_type_police
km_accurate
km_raw
non_urban_intersection_by_junction_number
rsa_severity
rsa_license_plate

In [30]:
import pandas as pd
df_markers = pd.DataFrame(markers, columns = column_names)
df_markers.set_index('id', inplace=True)

In [31]:
df_markers.head()

,latitude,longitude,type,title,created,provider_code,description,address,mainStreet,secondaryStreet,...,municipal_status,vehicle_type_rsa,violation_type_rsa,house_number,file_type_police,km_accurate,km_raw,non_urban_intersection_by_junction_number,rsa_severity,rsa_license_plate
id,,,,,,,,,,,,,,,,,,,,,
2008000492,32.425055,34.907661,None,Accident,2008-01-01 00:15:00,3,"{""SUG_DEREH"": 4.0, ""YEHIDA"": 11.0, ""SUG_YOM"": ...",,,,...,NaN,None,None,NaN,None,True,1580,None,None,None
2008000760,32.073014,34.767923,None,Accident,2008-01-01 00:30:00,1,"{""REHOV1"": ""\u05d4\u05db\u05d5\u05d1\u05e9\u05...","הכובשים, תל אביב -יפו","הכובשים, תל אביב -יפו",אלנבי,...,NaN,None,None,NaN,None,None,None,None,None,None
2008001278,32.712856,35.303071,None,Accident,2008-01-01 01:00:00,1,"{""REHOV1"": ""\u05e8\u05d7 7000 25, \u05e0\u05e6...","רח 7000 25, נצרת","רח 7000 25, נצרת",,...,NaN,None,None,25.0,None,None,None,None,None,None
2008001265,31.793830,35.226808,None,Accident,2008-01-01 01:00:00,3,"{""REHOV1"": ""\u05d3\u05e8\u05da \u05d1\u05e8-\u...","דרך בר-לב, ירושלים","דרך בר-לב, ירושלים",,...,NaN,None,None,9999.0,None,None,None,None,None,None
2008001392,32.087097,34.888220,None,Accident,2008-01-01 01:00:00,3,"{""SUG_DEREH"": 2.0, ""YEHIDA"": 51.0, ""SUG_YOM"": ...",,,,...,NaN,None,None,9999.0,None,None,None,None,None,None

In [32]:
df_markers.at[2008000492, 'created']

Timestamp('2008-01-01 00:15:00')

In [33]:
query = "SELECT * FROM markers WHERE (accident_day = 31 AND accident_month = 8 AND accident_year = 2019) ORDER BY created ASC"
cur.execute(query)
accident_markers_from_31_08_2019 = cur.fetchall()

In [34]:
df_from_31_08_2019 = pd.DataFrame(accident_markers_from_31_08_2019, columns = column_names)
df_from_31_08_2019.set_index('id', inplace=True)

In [35]:
df_from_31_08_2019.head()

,latitude,longitude,type,title,created,provider_code,description,address,mainStreet,secondaryStreet,...,municipal_status,vehicle_type_rsa,violation_type_rsa,house_number,file_type_police,km_accurate,km_raw,non_urban_intersection_by_junction_number,rsa_severity,rsa_license_plate
id,,,,,,,,,,,,,,,,,,,,,
2019005289,32.803732,35.008811,None,Accident,2019-08-31 00:30:00,3,"{""SUG_DEREH"": 2.0, ""YEHIDA"": 11.0, ""SUG_YOM"": ...",,,,...,0.0,None,None,9999.0,3,None,None,None,None,None
2019076192,32.028421,34.886008,None,Accident,2019-08-31 01:15:00,1,"{""REHOV1"": ""\u05d4\u05e8\u05e6\u05dc 1, \u05d9...","הרצל 1, יהוד","הרצל 1, יהוד",,...,0.0,None,None,1.0,1,None,None,None,None,None
2019047081,31.266159,34.798151,None,Accident,2019-08-31 01:15:00,1,"{""REHOV1"": ""\u05e9\u05d3 \u05e8\u05d2\u05e8 \u...","שד רגר יצחק, באר שבע","שד רגר יצחק, באר שבע",הרב סוסו יוסף,...,0.0,None,None,NaN,1,None,None,None,None,None
2019091041,32.915632,35.309763,None,Accident,2019-08-31 02:00:00,3,"{""REHOV1"": ""\u05d3\u05e8\u05da \u05d4\u05ea\u0...","דרך התעשייה, כרמיאל","דרך התעשייה, כרמיאל",,...,0.0,None,None,9999.0,3,None,None,None,None,None
2019034925,32.787607,35.524466,None,Accident,2019-08-31 02:00:00,3,"{""SUG_DEREH"": 2.0, ""YEHIDA"": 12.0, ""SUG_YOM"": ...",,,,...,0.0,None,None,9999.0,3,None,None,None,None,None

In [36]:
# mainStreet
# secondaryStreet
# street1
# street2
# street1_hebrew
# street2_hebrew

In [37]:
is_time_23 = (df_from_31_08_2019['created'] > '2019-08-31 21:30:00') & (df_from_31_08_2019['created'] < '2019-08-31 23:30:00')

In [38]:
accidents_from_23 = df_from_31_08_2019[is_time_23]

In [39]:
accidents_from_23

,latitude,longitude,type,title,created,provider_code,description,address,mainStreet,secondaryStreet,...,municipal_status,vehicle_type_rsa,violation_type_rsa,house_number,file_type_police,km_accurate,km_raw,non_urban_intersection_by_junction_number,rsa_severity,rsa_license_plate
id,,,,,,,,,,,,,,,,,,,,,
2019022308,32.311986,34.999224,None,Accident,2019-08-31 22:00:00,3,"{""SHEM_ZOMET"": ""\u05e6\u05d5\u05de\u05ea \u05e...",,,,...,NaN,None,None,NaN,3,True,126,צומת ניצני עוז,None,None
2019009154,32.279347,34.860635,None,Accident,2019-08-31 22:00:00,3,"{""REHOV1"": ""\u05d2\u05d1\u05d5\u05e8\u05d9 \u0...","גבורי ישראל, נתניה","גבורי ישראל, נתניה",,...,0.0,None,None,9999.0,3,None,None,None,None,None
2019022409,31.798408,35.143050,None,Accident,2019-08-31 22:30:00,3,"{""SUG_DEREH"": 4.0, ""YEHIDA"": 61.0, ""SUG_YOM"": ...",,,,...,NaN,None,None,NaN,3,True,510,None,None,None
2019008086,31.798408,35.143050,None,Accident,2019-08-31 22:30:00,3,"{""SUG_DEREH"": 4.0, ""YEHIDA"": 61.0, ""SUG_YOM"": ...",,,,...,NaN,None,None,NaN,3,True,510,None,None,None
2019066872,32.917861,35.112750,None,Accident,2019-08-31 22:30:00,3,"{""SUG_DEREH"": 4.0, ""YEHIDA"": 12.0, ""SUG_YOM"": ...",,,,...,NaN,None,None,NaN,3,True,30,None,None,None
2019008105,32.986606,35.439880,None,Accident,2019-08-31 23:00:00,3,"{""SUG_DEREH"": 2.0, ""YEHIDA"": 51.0, ""SUG_YOM"": ...",,,,...,2.0,None,None,9999.0,3,None,None,None,None,None
2019064279,32.264835,35.006388,None,Accident,2019-08-31 23:00:00,1,"{""SUG_DEREH"": 2.0, ""YEHIDA"": 51.0, ""SUG_YOM"": ...",,,,...,0.0,None,None,9999.0,1,None,None,None,None,None
2019004597,31.814588,35.238346,None,Accident,2019-08-31 23:00:00,3,"{""REHOV1"": ""\u05d4\u05d0\u05dc\u05d5\u05e3 \u0...","האלוף עוזי נרקיס, ירושלים","האלוף עוזי נרקיס, ירושלים",,...,0.0,None,None,9999.0,3,None,None,None,None,None
2019011929,32.048918,34.958890,None,Accident,2019-08-31 23:00:00,1,"{""REHOV1"": ""\u05e8\u05d1\u05d9 \u05d9\u05d5\u0...","רבי יונתן בן עוזי 12, אלעד","רבי יונתן בן עוזי 12, אלעד",,...,0.0,None,None,12.0,1,None,None,None,None,None

In [40]:
query = "SELECT * FROM markers WHERE (accident_day = 1 AND accident_month = 9 AND accident_year = 2019) ORDER BY created ASC"
cur.execute(query)
accident_markers_from_01_09_2019 = cur.fetchall()

In [41]:
df_from_01_09_2019 = pd.DataFrame(accident_markers_from_01_09_2019, columns = column_names)
df_from_01_09_2019.set_index('id', inplace=True)

In [42]:
df_from_01_09_2019.head()

,latitude,longitude,type,title,created,provider_code,description,address,mainStreet,secondaryStreet,...,municipal_status,vehicle_type_rsa,violation_type_rsa,house_number,file_type_police,km_accurate,km_raw,non_urban_intersection_by_junction_number,rsa_severity,rsa_license_plate
id,,,,,,,,,,,,,,,,,,,,,
2019092912,32.864732,35.299232,None,Accident,2019-09-01 00:15:00,3,"{""SUG_DEREH"": 2.0, ""YEHIDA"": 12.0, ""SUG_YOM"": ...",,,,...,0.0,None,None,9999.0,3,None,None,None,None,None
2019083340,31.800933,34.646503,None,Accident,2019-09-01 00:30:00,3,"{""REHOV1"": ""\u05e9\u05d3 \u05d4\u05e8\u05e6\u0...","שד הרצל, אשדוד","שד הרצל, אשדוד",,...,0.0,None,None,9999.0,3,None,None,None,None,None
2019062393,32.000573,34.829879,None,Accident,2019-09-01 01:15:00,1,"{""SUG_DEREH"": 2.0, ""YEHIDA"": 52.0, ""SUG_YOM"": ...",,,,...,99.0,None,None,9999.0,1,None,None,None,None,None
2019046199,31.838982,34.986989,None,Accident,2019-09-01 02:00:00,3,"{""SHEM_ZOMET"": ""\u05de\u05d7\u05dc\u05e3 \u05d...",,,,...,NaN,None,None,NaN,3,True,336,מחלף לטרון,None,None
2019018272,32.051923,34.768458,None,Accident,2019-09-01 02:30:00,3,"{""REHOV1"": ""\u05e7\u05d1\u05d5\u05e5 \u05d2\u0...","קבוץ גלויות 34, תל אביב -יפו","קבוץ גלויות 34, תל אביב -יפו",,...,0.0,None,None,34.0,3,None,None,None,None,None

In [43]:
df_from_01_09_2019.at[2019092912,'description']

'{"SUG_DEREH": 2.0, "YEHIDA": 12.0, "SUG_YOM": 4.0, "HUMRAT_TEUNA": 3.0, "SUG_TEUNA": 8.0, "ZURAT_DEREH": 9.0, "STATUS_IGUN": 2.0}'

In [44]:
query = "SELECT * FROM markers WHERE (accident_day = 2 AND accident_month = 9 AND accident_year = 2019) ORDER BY created ASC"
cur.execute(query)
accident_markers_from_02_09_2019 = cur.fetchall()

In [45]:
df_from_02_09_2019 = pd.DataFrame(accident_markers_from_02_09_2019, columns = column_names)
df_from_02_09_2019.set_index('id', inplace=True)

In [46]:
df_from_02_09_2019

,latitude,longitude,type,title,created,provider_code,description,address,mainStreet,secondaryStreet,...,municipal_status,vehicle_type_rsa,violation_type_rsa,house_number,file_type_police,km_accurate,km_raw,non_urban_intersection_by_junction_number,rsa_severity,rsa_license_plate
id,,,,,,,,,,,,,,,,,,,,,
2019042645,31.820745,35.443190,None,Accident,2019-09-02 00:00:00,1,"{""SUG_DEREH"": 4.0, ""YEHIDA"": 43.0, ""SUG_YOM"": ...",,,,...,99.0,None,None,NaN,1,True,0,None,None,None
2019029641,32.065381,34.777194,None,Accident,2019-09-02 01:45:00,3,"{""REHOV1"": ""\u05e0\u05d7\u05de\u05e0\u05d9 33,...","נחמני 33, תל אביב -יפו","נחמני 33, תל אביב -יפו",,...,0.0,None,None,33.0,3,None,None,None,None,None
2019058718,31.782239,34.705305,None,Accident,2019-09-02 01:45:00,1,"{""REHOV1"": ""\u05d4\u05e8\u05e6\u05dc, \u05d2\u...","הרצל, גן יבנה","הרצל, גן יבנה",הנצחון,...,99.0,None,None,NaN,1,None,None,None,None,None
2019038496,32.961161,35.168280,None,Accident,2019-09-02 02:15:00,1,"{""SUG_DEREH"": 2.0, ""YEHIDA"": 12.0, ""SUG_YOM"": ...",,,,...,99.0,None,None,9999.0,1,None,None,None,None,None
2019090681,32.081928,34.873229,None,Accident,2019-09-02 02:15:00,3,"{""REHOV1"": ""\u05d3\u05d2\u05dc \u05e8\u05d0\u0...","דגל ראובן, פתח תקווה","דגל ראובן, פתח תקווה",ויצמן,...,0.0,None,None,NaN,3,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2019024374,32.016734,34.778648,None,Accident,2019-09-02 21:15:00,3,"{""SUG_DEREH"": 2.0, ""YEHIDA"": 20.0, ""SUG_YOM"": ...",,,,...,0.0,None,None,9999.0,3,None,None,None,None,None
2019043143,32.080896,34.820940,None,Accident,2019-09-02 21:30:00,3,"{""REHOV1"": ""\u05d4\u05de\u05d9\u05ea\u05e8 25,...","המיתר 25, רמת גן","המיתר 25, רמת גן",,...,0.0,None,None,25.0,3,None,None,None,None,None
2019086042,32.019240,34.752248,None,Accident,2019-09-02 22:00:00,3,"{""REHOV1"": ""\u05e8\u05de\u05d6 9, \u05d1\u05ea...","רמז 9, בת ים","רמז 9, בת ים",,...,0.0,None,None,9.0,3,None,None,None,None,None
2019002062,32.832496,35.054192,None,Accident,2019-09-02 22:00:00,3,"{""REHOV1"": ""\u05e9\u05d3 \u05d3\u05d2\u05e0\u0...","שד דגניה 54, חיפה","שד דגניה 54, חיפה",,...,0.0,None,None,54.0,3,None,None,None,None,None
2019062127,32.020808,34.953705,None,Accident,2019-09-02 22:30:00,1,"{""SUG_DEREH"": 4.0, ""YEHIDA"": 51.0, ""SUG_YOM"": ...",,,,...,99.0,None,None,NaN,1,True,110,None,None,None

In [48]:
df_from_02_09_2019['address'].unique()

array(['', 'נחמני 33, תל אביב -יפו', 'הרצל, גן יבנה',
       'דגל ראובן, פתח תקווה', 'פופל מרדכי, ראשון לציון',
       'שד גולדה מאיר, ירושלים', 'שמגר, ירושלים', 'דרך הים, רחובות',
       'חטיבה תשע, עפולה', 'רייך בני, נתניה', 'יוספטל, אשקלון',
       'מבצע נחשון, מודיעין-מכבים-רעות*', 'שד המגינים, חיפה',
       'הלפרין, ראשון לציון', 'ההגנה, רמלה', 'רותם, עומר',
       'יוסף, מודיעין-מכבים-רעות*', 'כהן אלי 4, בת ים',
       'סמ זבוטינסקי, חדרה', 'שד החברה הכלכלית, מעלה אדומים',
       'בן יהודה, פתח תקווה', 'יהודה לייב, ראשון לציון',
       'דרך בר-לב חיים, תל אביב -יפו', 'ההגנה, רעננה',
       'נחל פארן, מודיעין-מכבים-רעות*', "ז'בוטינסקי, תל אביב -יפו",
       'שד ההסתדרות, חיפה', 'דרך בן גוריון דוד 38, רמת גן',
       'המצודה, חולון', "ז'בוטינסקי 169, בני ברק", 'הקוממיות, בת ים',
       'ההסתדרות, חולון', 'סוקולוב 6, הרצלייה', 'אלון יגאל, תל אביב -יפו',
       'אבן גבירול, תל אביב -יפו', 'המלאכה, חולון', 'בשיסט מרדכי, רחובות',
       'שד יעקב, ראשון לציון', 'שנקר, חולון', 'שד העצמאות, בת ים',
       'הרב קוק, הרצלייה', 'פינסקר, נתניה', 'הסיבים, פתח תקווה',
       'הרצל 11, קדימה-צורן', 'שד השופטים, קריית גת', 'ויצמן, רעננה',
       'בלפור 142, בת ים', 'החלוצים, בני ברק', 'ששת הימים, כפר סבא',
       'ירושלים, ראשון לציון', 'דרך העמק, יקנעם (מושבה)',
       'שד ההגנה, חיפה', 'דרך יפו, תל אביב -יפו',
       'זרובבל יעקב, פתח תקווה', 'אליאב יעקב 2, ירושלים',
       'ירושלים, בת ים', 'המדע, רחובות', 'זבולון, קריית אתא',
       'יוספטל גיורא, לוד', 'דרך שועפאט, ירושלים',
       'גליקסון, תל אביב -יפו', 'שד אלטלנה, אשדוד',
       'בית הדפוס 12, ירושלים', 'עזה, ירושלים', 'צה"ל, ראש העין',
       'דרך יצחק רבין, קריית אתא', 'הרב אגן, ירושלים', 'כצנלסון, גבעתיים',
       'שד בגין מנחם, רחובות', 'הלל, חיפה', 'הירקונים, פתח תקווה',
       'נתנזון 43, חיפה', 'כורזין, גבעתיים', 'שד טוביהו דוד, באר שבע',
       'דרך חיפה, קריית אתא', 'אילות 143, אילת', 'שד ירושלים, קריית ים',
       'אבן גבירול 176, תל אביב -יפו', 'עציון גבר, תל אביב -יפו',
       'קדושי יאסי, חיפה', 'חרל"פ, רחובות',
       'קויפמן יחזקאל 10, תל אביב -יפו', 'סמ במעלה, רמת השרון',
       'דיין משה, חולון', 'אילת 52, תל אביב -יפו',
       'החשמונאים, קריית מוצקין', 'דרך בן צבי 35, תל אביב -יפו',
       'נחל שחם, בית שמש', 'המחשב, נתניה', 'מעלה השלום, ירושלים',
       "ז'בוטינסקי, בני ברק", 'מקוה ישראל, חולון', 'יהודה הלוי, באר שבע',
       'הערבה 4, קריית מוצקין', 'שטריקר, תל אביב -יפו',
       "פרופ' שור 20, חולון", 'לניאדו עזרא, טירת כרמל', 'מצדה, אריאל',
       'כצנלסון 52, גבעתיים', 'אברהם אבינו 4, באר שבע',
       'דרך בגין, תל אביב -יפו', 'בן צבי שמעון 19, גבעתיים',
       'ויצמן, נס ציונה', "ז'בוטינסקי, יבנה", 'הרצל, כפר יונה',
       'בן גוריון, רחובות', 'חטיבת גולני, עכו', 'פרי מגדים, מעלה אדומים',
       'פינס יחיאל מיכל 2, פתח תקווה', 'צונץ, תל אביב -יפו',
       'דרך ההגנה 88, תל אביב -יפו', 'וולפסון, חיפה',
       'ישעיהו הנביא, בית שמש', 'ביאליק, קריית אתא',
       'אשכול לוי, קריית אונו', 'דרך בן צבי, תל אביב -יפו',
       'חשמונאים 30, גן יבנה', 'רש"י, בית שמש',
       'חיל השריון, תל אביב -יפו', 'נהר הירדן, בית שמש',
       'המיתר 25, רמת גן', 'רמז 9, בת ים', 'שד דגניה 54, חיפה'],
      dtype=object)

In [50]:
df_tel_aviv_accidents = df_from_02_09_2019[df_from_02_09_2019['address'].str.contains('תל אביב -יפו')]

In [51]:
df_tel_aviv_accidents

,latitude,longitude,type,title,created,provider_code,description,address,mainStreet,secondaryStreet,...,municipal_status,vehicle_type_rsa,violation_type_rsa,house_number,file_type_police,km_accurate,km_raw,non_urban_intersection_by_junction_number,rsa_severity,rsa_license_plate
id,,,,,,,,,,,,,,,,,,,,,
2019029641,32.065381,34.777194,None,Accident,2019-09-02 01:45:00,3,"{""REHOV1"": ""\u05e0\u05d7\u05de\u05e0\u05d9 33,...","נחמני 33, תל אביב -יפו","נחמני 33, תל אביב -יפו",,...,0.0,None,None,33.0,3,None,None,None,None,None
2019066125,32.045645,34.806360,None,Accident,2019-09-02 08:15:00,1,"{""REHOV1"": ""\u05d3\u05e8\u05da \u05d1\u05e8-\u...","דרך בר-לב חיים, תל אביב -יפו","דרך בר-לב חיים, תל אביב -יפו",לובטקין צביה,...,0.0,None,None,NaN,1,None,None,None,None,None
2019050032,32.087097,34.788427,None,Accident,2019-09-02 08:30:00,3,"{""REHOV1"": ""\u05d6'\u05d1\u05d5\u05d8\u05d9\u0...","ז'בוטינסקי, תל אביב -יפו","ז'בוטינסקי, תל אביב -יפו",הא באייר,...,0.0,None,None,NaN,3,None,None,None,None,None
2019078250,32.067336,34.793039,None,Accident,2019-09-02 10:15:00,3,"{""REHOV1"": ""\u05d0\u05dc\u05d5\u05df \u05d9\u0...","אלון יגאל, תל אביב -יפו","אלון יגאל, תל אביב -יפו",,...,0.0,None,None,9999.0,3,None,None,None,None,None
2019060200,32.091038,34.782943,None,Accident,2019-09-02 10:15:00,1,"{""REHOV1"": ""\u05d0\u05d1\u05df \u05d2\u05d1\u0...","אבן גבירול, תל אביב -יפו","אבן גבירול, תל אביב -יפו",פנקס,...,0.0,None,None,NaN,1,None,None,None,None,None
2019045213,32.060624,34.770619,None,Accident,2019-09-02 13:00:00,3,"{""REHOV1"": ""\u05d3\u05e8\u05da \u05d9\u05e4\u0...","דרך יפו, תל אביב -יפו","דרך יפו, תל אביב -יפו",,...,0.0,None,None,9999.0,3,None,None,None,None,None
2019021430,32.077422,34.772446,None,Accident,2019-09-02 13:00:00,3,"{""REHOV1"": ""\u05d2\u05dc\u05d9\u05e7\u05e1\u05...","גליקסון, תל אביב -יפו","גליקסון, תל אביב -יפו",,...,0.0,None,None,9999.0,3,None,None,None,None,None
2019088917,32.092933,34.783305,None,Accident,2019-09-02 15:00:00,3,"{""REHOV1"": ""\u05d0\u05d1\u05df \u05d2\u05d1\u0...","אבן גבירול 176, תל אביב -יפו","אבן גבירול 176, תל אביב -יפו",,...,0.0,None,None,176.0,3,None,None,None,None,None
2019063577,32.054759,34.761720,None,Accident,2019-09-02 15:00:00,1,"{""REHOV1"": ""\u05e2\u05e6\u05d9\u05d5\u05df \u0...","עציון גבר, תל אביב -יפו","עציון גבר, תל אביב -יפו",דרך שלמה,...,0.0,None,None,NaN,1,None,None,None,None,None
2019066681,32.065169,34.762634,None,Accident,2019-09-02 15:15:00,1,"{""REHOV1"": ""\u05e7\u05d5\u05d9\u05e4\u05de\u05...","קויפמן יחזקאל 10, תל אביב -יפו","קויפמן יחזקאל 10, תל אביב -יפו",,...,0.0,None,None,10.0,1,None,None,None,None,None
2019043385,32.059339,34.766696,None,Accident,2019-09-02 15:30:00,3,"{""REHOV1"": ""\u05d0\u05d9\u05dc\u05ea 52, \u05e...","אילת 52, תל אביב -יפו","אילת 52, תל אביב -יפו",,...,0.0,None,None,52.0,3,None,None,None,None,None
2019070859,32.048653,34.764015,None,Accident,2019-09-02 16:00:00,3,"{""REHOV1"": ""\u05d3\u05e8\u05da \u05d1\u05df \u...","דרך בן צבי 35, תל אביב -יפו","דרך בן צבי 35, תל אביב -יפו",,...,0.0,None,None,35.0,3,None,None,None,None,None
2019023417,32.092597,34.788042,None,Accident,2019-09-02 17:00:00,3,"{""REHOV1"": ""\u05e9\u05d8\u05e8\u05d9\u05e7\u05...","שטריקר, תל אביב -יפו","שטריקר, תל אביב -יפו",לואי מרשל,...,0.0,None,None,NaN,3,None,None,None,None,None
2019047790,32.071139,34.789347,None,Accident,2019-09-02 17:15:00,3,"{""REHOV1"": ""\u05d3\u05e8\u05da \u05d1\u05d2\u0...","דרך בגין, תל אביב -יפו","דרך בגין, תל אביב -יפו",,...,0.0,None,None,9999.0,3,None,None,None,None,None
2019055380,32.043091,34.764720,None,Accident,2019-09-02 18:30:00,3,"{""REHOV1"": ""\u05e6\u05d5\u05e0\u05e5, \u05ea\u...","צונץ, תל אביב -יפו","צונץ, תל אביב -יפו",,...,0.0,None,None,9999.0,3,None,None,None,None,None
2019043859,32.054039,34.791616,None,Accident,2019-09-02 18:45:00,1,"{""REHOV1"": ""\u05d3\u05e8\u05da \u05d4\u05d4\u0...","דרך ההגנה 88, תל אביב -יפו","דרך ההגנה 88, תל אביב -יפו",,...,0.0,None,None,88.0,1,None,None,None,None,None
2019082710,32.050029,34.760409,None,Accident,2019-09-02 19:30:00,3,"{""REHOV1"": ""\u05d3\u05e8\u05da \u05d1\u05df \u...","דרך בן צבי, תל אביב -יפו","דרך בן צבי, תל אביב -יפו",יהודה הימית,...,0.0,None,None,NaN,3,None,None,None,None,None
2019021138,32.047042,34.783738,None,Accident,2019-09-02 20:30:00,3,"{""REHOV1"": ""\u05d7\u05d9\u05dc \u05d4\u05e9\u0...","חיל השריון, תל אביב -יפו","חיל השריון, תל אביב -יפו",קבוץ גלויות,...,0.0,None,None,NaN,3,None,None,None,None,None

In [52]:
waze_tel_aviv_streets = ['דרך חיים בר-לב', 'אליעזר קפלן', 'דרך נמיר',
       'יגאל אלון', 'חניון מרכז הספורט הלאומי', 'פנקס', 'הברזל', 'שלבים',
       'אבן גבירול', 'המרד', 'דרך בגין', 'אלנבי', 'דרך שלמה',
       'דרך חיל השריון', 'נס לגויים', 'דיזנגוף', 'הירקון', 'המסגר',
       'משה סנה', 'ירוחם משל', 'קהילת ונציה']
# deleted שד' רוקח

In [53]:
df_Ibn_Gabirol_accidents = df_from_02_09_2019[df_from_02_09_2019['address'].str.contains('אבן גבירול')]

In [54]:
df_Ibn_Gabirol_accidents

,latitude,longitude,type,title,created,provider_code,description,address,mainStreet,secondaryStreet,...,municipal_status,vehicle_type_rsa,violation_type_rsa,house_number,file_type_police,km_accurate,km_raw,non_urban_intersection_by_junction_number,rsa_severity,rsa_license_plate
id,,,,,,,,,,,,,,,,,,,,,
2019060200,32.091038,34.782943,None,Accident,2019-09-02 10:15:00,1,"{""REHOV1"": ""\u05d0\u05d1\u05df \u05d2\u05d1\u0...","אבן גבירול, תל אביב -יפו","אבן גבירול, תל אביב -יפו",פנקס,...,0.0,None,None,NaN,1,None,None,None,None,None
2019088917,32.092933,34.783305,None,Accident,2019-09-02 15:00:00,3,"{""REHOV1"": ""\u05d0\u05d1\u05df \u05d2\u05d1\u0...","אבן גבירול 176, תל אביב -יפו","אבן גבירול 176, תל אביב -יפו",,...,0.0,None,None,176.0,3,None,None,None,None,None

In [58]:
df_Ibn_Gabirol_accidents.at[2019060200,'location_accuracy']

1