In [1]:
import psycopg2

In [2]:
conn = psycopg2.connect(dbname="anyway", user="anyway", password="anyway", host="db")

In [3]:
cur = conn.cursor()

In [4]:
query = "SELECT * FROM waze_alerts ORDER BY created_at ASC"
cur.execute(query)
waze_alerts = cur.fetchall()

In [5]:
column_names = [desc[0] for desc in cur.description]
for column in column_names:
    print(column)

id
city
confidence
created_at
lontitude
latitude
magvar
number_thumbs_up
report_rating
reliability
alert_type
alert_subtype
uuid
street
road_type
geom

In [6]:
import pandas as pd
df_waze_alerts = pd.DataFrame(waze_alerts, columns = column_names)

In [7]:
df_waze_alerts.head()

,id,city,confidence,created_at,lontitude,latitude,magvar,number_thumbs_up,report_rating,reliability,alert_type,alert_subtype,uuid,street,road_type,geom
0,137,רעננה,5,2018-09-03 09:52:26,32.199554,34.880845,0,0,0,10,ROAD_CLOSED,ROAD_CLOSED_EVENT,05dfa50e-1159-3d4a-b769-921d194b1715,דולב,-1,01010000009BE447FC8A1940402DEC6987BF704140
1,385,רעננה,5,2018-09-03 09:52:26,32.199554,34.880845,0,0,0,10,ROAD_CLOSED,ROAD_CLOSED_EVENT,05dfa50e-1159-3d4a-b769-921d194b1715,דולב,-1,01010000009BE447FC8A1940402DEC6987BF704140
2,630,רעננה,5,2018-09-03 09:52:26,32.199554,34.880845,0,0,0,10,ROAD_CLOSED,ROAD_CLOSED_EVENT,05dfa50e-1159-3d4a-b769-921d194b1715,דולב,-1,01010000009BE447FC8A1940402DEC6987BF704140
3,873,רעננה,5,2018-09-03 09:52:26,32.199554,34.880845,0,0,0,10,ROAD_CLOSED,ROAD_CLOSED_EVENT,05dfa50e-1159-3d4a-b769-921d194b1715,דולב,-1,01010000009BE447FC8A1940402DEC6987BF704140
4,1114,רעננה,5,2018-09-03 09:52:26,32.199554,34.880845,0,0,0,10,ROAD_CLOSED,ROAD_CLOSED_EVENT,05dfa50e-1159-3d4a-b769-921d194b1715,דולב,-1,01010000009BE447FC8A1940402DEC6987BF704140

In [8]:
df_waze_alerts.tail()

,id,city,confidence,created_at,lontitude,latitude,magvar,number_thumbs_up,report_rating,reliability,alert_type,alert_subtype,uuid,street,road_type,geom
350663,350623,NaN,0,2019-09-02 23:54:46,32.492653,34.918129,183,0,5,5,WEATHERHAZARD,,8bdc06f5-1036-3222-b2d5-66ecafb5a022,2 דרום,3,01010000005DA3E5400F3F40402D41464085754140
350664,350668,NaN,0,2019-09-02 23:54:46,32.589856,35.236702,65,0,5,5,WEATHERHAZARD,HAZARD_ON_ROAD_CONSTRUCTION,25c0fd4f-40aa-32ce-a7d5-71f79ddbdf59,65 מזרח,6,0101000000B8ACC266804B4040EB724A404C9E4140
350665,350604,NaN,0,2019-09-02 23:55:21,31.834663,35.175128,54,0,5,5,WEATHERHAZARD,HAZARD_ON_ROAD_CAR_STOPPED,99b649a6-35e3-3320-873e-c694249dcbe6,436,7,0101000000662E7079ACD53F40944E24986A964140
350666,350434,NaN,0,2019-09-02 23:55:34,31.992058,34.867524,237,0,4,5,JAM,JAM_STAND_STILL_TRAFFIC,c5ec2f71-7a97-322f-985f-a03859611321,הנתיב המהיר,3,010100000034BC5983F7FD3F40603FC4060B6F4140
350667,350601,ירושלים,0,2019-09-02 23:55:45,31.781430,35.211910,89,0,5,5,ROAD_CLOSED,ROAD_CLOSED_CONSTRUCTION,68238c46-ac66-3367-bc85-bffdd9547b3e,בצלאל,2,0101000000001DE6CB0BC83F4002D9EBDD1F9B4140

In [9]:
df_waze_alerts.set_index('id',inplace=True)

In [10]:
df_waze_accidents = df_waze_alerts[df_waze_alerts["alert_type"] == 'ACCIDENT']

In [11]:
df_waze_accidents.shape

(7039, 15)

In [12]:
df_waze_accidents.head()

,city,confidence,created_at,lontitude,latitude,magvar,number_thumbs_up,report_rating,reliability,alert_type,alert_subtype,uuid,street,road_type,geom
id,,,,,,,,,,,,,,,
23,NaN,2,2019-08-31 23:16:13,31.577055,34.806770,190,0,5,10,ACCIDENT,,157ff0c3-ebd5-3c5b-a88e-0e6e283acdb9,6 דרום,3,010100000048FE60E0B9933F406CB2463D44674140
272,NaN,3,2019-08-31 23:16:13,31.577055,34.806770,190,0,5,10,ACCIDENT,,157ff0c3-ebd5-3c5b-a88e-0e6e283acdb9,6 דרום,3,010100000048FE60E0B9933F406CB2463D44674140
521,NaN,3,2019-08-31 23:16:13,31.577055,34.806770,190,0,5,10,ACCIDENT,,157ff0c3-ebd5-3c5b-a88e-0e6e283acdb9,6 דרום,3,010100000048FE60E0B9933F406CB2463D44674140
764,NaN,3,2019-08-31 23:16:13,31.577055,34.806770,190,0,5,10,ACCIDENT,,157ff0c3-ebd5-3c5b-a88e-0e6e283acdb9,6 דרום,3,010100000048FE60E0B9933F406CB2463D44674140
3916,NaN,0,2019-09-01 00:55:23,31.836798,34.987609,346,0,5,5,ACCIDENT,,43cf9e73-1d41-3968-9cb4-f220ce31c1d0,1 מערב,3,0101000000B45BCB6438D63F401D1EC2F8697E4140

In [13]:
timestamp = df_waze_accidents.at[23,'created_at']

In [14]:
timestamp.date()

datetime.date(2019, 8, 31)

In [15]:
waze_accident_dates = df_waze_accidents['created_at'].apply(lambda created_at: created_at.date())

In [16]:
waze_accident_dates

id
23        2019-08-31
272       2019-08-31
521       2019-08-31
764       2019-08-31
3916      2019-09-01
             ...
346700    2019-09-02
346999    2019-09-02
347292    2019-09-02
350107    2019-09-02
350394    2019-09-02
Name: created_at, Length: 7039, dtype: object

In [17]:
waze_accident_dates.unique()

array([datetime.date(2019, 8, 31), datetime.date(2019, 9, 1),
       datetime.date(2019, 9, 2)], dtype=object)

In [18]:
query = "SELECT DISTINCT alert_type FROM waze_alerts"
cur.execute(query)
alert_types = cur.fetchall()

In [19]:
alert_types

[('ROAD_CLOSED',), ('JAM',), ('WEATHERHAZARD',), ('ACCIDENT',)]

In [20]:
df_waze_accidents['confidence'].value_counts()

0    4308
1     869
5     867
2     442
3     312
4     241
Name: confidence, dtype: int64

In [21]:
df_waze_accidents['number_thumbs_up'].value_counts()

0    7039
Name: number_thumbs_up, dtype: int64

In [22]:
df_waze_accidents['report_rating'].value_counts()

5    5376
1     695
0     306
4     282
3     199
2     181
Name: report_rating, dtype: int64

In [23]:
df_waze_accidents['reliability'].value_counts()

5     2887
10    1759
6     1119
7      639
8      358
9      277
Name: reliability, dtype: int64

In [24]:
df_waze_accidents['street'].value_counts()

NaN             1060
4 צפון           244
4 דרום           138
6 דרום           130
85 מזרח          109
                ...
5815               1
דרך שלמה           1
ירמיהו             1
הארי טרומן         1
שבעת הכוכבים       1
Name: street, Length: 447, dtype: int64

In [25]:
df_waze_accidents['road_type'].value_counts()

 6     2015
 2     1913
 3     1154
 1      812
 7      434
 4      434
-1      138
 20      78
 8       36
 17      18
 5        7
Name: road_type, dtype: int64

In [26]:
df_waze_accidents['city'].unique()

array(['NaN', 'נמל תעופה בן גוריון', 'כפר כנא', 'שוהם', 'רמת גן',
       'באר שבע', 'נצרת', 'ראש העין', 'עין בוקק', 'ירושלים',
       'תל אביב - יפו', 'חיפה', 'נהריה', 'טייבה', 'צפת', 'כסרא-סמיע',
       'עפולה', 'קריית אונו', 'רעננה', 'פתח תקווה', 'רמת השרון', 'בת ים',
       'אכסאל', 'גבעתיים', 'מודיעין-מכבים-רעות', 'כפר מנדא', 'אשדוד',
       'ריינה', 'בני ברק', 'אבן יהודה', 'כסיפה', 'נתניה', 'רמלה',
       'הרצליה', 'יהוד - נווה אפרים', 'להבים', 'קריית אתא', 'גבעת זאב',
       'כפר יונה', 'Jericho - أريحا', 'אופקים', 'קדימה', 'חבצלת השרון',
       'Halhul - حلحول', 'קריית מלאכי', 'חדרה', 'חולון',
       'פארק תעשייה בר - לב', 'קריית גת', 'כפר סבא', 'באר יעקב',
       'ראשון לציון', 'סביון', 'באקה אל-גרביה', 'בני עי"ש', 'קריית טבעון',
       'יקנעם עילית', 'פרדס חנה-כרכור', "ג'ת", 'מעלה שומרון',
       'קריית עקרון', 'משמר הנגב', 'שפרעם', 'זכרון יעקב', 'קריית ביאליק',
       "יאנוח-ג'ת", 'יד בנימין', "כעביה-טבאש-חג'אג'", 'רמת דוד',
       'Fawwar - مخيم الفوار', 'רחובות', 'מבוא חורון', 'מזכרת בתיה',
       'אשקלון', 'הוד השרון', 'נשר', 'עומר', 'נס ציונה', 'אור עקיבא',
       'רומאנה', 'מעיליא', 'אזור', 'מעלה אדומים', 'טבריה', 'קריית מוצקין',
       'Ramallah - رام الله', 'כפר שמריהו', 'Dura - دورا', 'נצרת עילית',
       'כרם מהר"ל', 'מבשרת ציון', 'שדרות', 'זרזיר', 'Qibya - قبية\u200e',
       'מודיעין עילית', 'Hebron - الْخَلِيل\u200e', 'نوبا', 'רהט',
       'Bethlehem - بيت لحم', 'Tammun - طمّون', 'ביתר עילית', 'סולם'],
      dtype=object)

In [27]:
df_waze_accidents.at[23,'city']

'NaN'

In [29]:
# accidents from 31.08.2019
import datetime
date = datetime.date(2019, 8, 31)
is_from_31_08_2019 = df_waze_accidents['created_at'].apply(lambda created_at: created_at.date()) == date

In [30]:
is_from_31_08_2019

id
23         True
272        True
521        True
764        True
3916      False
          ...
346700    False
346999    False
347292    False
350107    False
350394    False
Name: created_at, Length: 7039, dtype: bool

In [31]:
accidents_from_31_08_2019 = df_waze_accidents[is_from_31_08_2019]

In [32]:
accidents_from_31_08_2019

,city,confidence,created_at,lontitude,latitude,magvar,number_thumbs_up,report_rating,reliability,alert_type,alert_subtype,uuid,street,road_type,geom
id,,,,,,,,,,,,,,,
23,NaN,2,2019-08-31 23:16:13,31.577055,34.80677,190,0,5,10,ACCIDENT,,157ff0c3-ebd5-3c5b-a88e-0e6e283acdb9,6 דרום,3,010100000048FE60E0B9933F406CB2463D44674140
272,NaN,3,2019-08-31 23:16:13,31.577055,34.80677,190,0,5,10,ACCIDENT,,157ff0c3-ebd5-3c5b-a88e-0e6e283acdb9,6 דרום,3,010100000048FE60E0B9933F406CB2463D44674140
521,NaN,3,2019-08-31 23:16:13,31.577055,34.80677,190,0,5,10,ACCIDENT,,157ff0c3-ebd5-3c5b-a88e-0e6e283acdb9,6 דרום,3,010100000048FE60E0B9933F406CB2463D44674140
764,NaN,3,2019-08-31 23:16:13,31.577055,34.80677,190,0,5,10,ACCIDENT,,157ff0c3-ebd5-3c5b-a88e-0e6e283acdb9,6 דרום,3,010100000048FE60E0B9933F406CB2463D44674140

In [33]:
# accidents from 01.09.2019
date = datetime.date(2019, 9, 1)
is_from_01_09_2019 = df_waze_accidents['created_at'].apply(lambda created_at: created_at.date()) == date

In [34]:
accidents_from_01_09_2019 = df_waze_accidents[is_from_01_09_2019]

In [35]:
accidents_from_01_09_2019.drop_duplicates()

,city,confidence,created_at,lontitude,latitude,magvar,number_thumbs_up,report_rating,reliability,alert_type,alert_subtype,uuid,street,road_type,geom
id,,,,,,,,,,,,,,,
3916,NaN,0,2019-09-01 00:55:23,31.836798,34.987609,346,0,5,5,ACCIDENT,,43cf9e73-1d41-3968-9cb4-f220ce31c1d0,1 מערב,3,0101000000B45BCB6438D63F401D1EC2F8697E4140
9216,NaN,1,2019-09-01 02:52:00,32.634163,35.064178,197,0,1,7,ACCIDENT,ACCIDENT_MAJOR,8aa5ceb2-5e33-363b-8638-f1d2876cd52a,6 דרום,3,0101000000A8AAD0402C514040B48F15FC36884140
9545,NaN,2,2019-09-01 02:52:00,32.634163,35.064178,197,0,1,10,ACCIDENT,ACCIDENT_MAJOR,8aa5ceb2-5e33-363b-8638-f1d2876cd52a,6 דרום,3,0101000000A8AAD0402C514040B48F15FC36884140
9516,NaN,0,2019-09-01 02:56:16,32.517678,34.929866,356,0,5,5,ACCIDENT,,8d97e0d9-06ed-3f39-bd25-5df4e3d03a8c,NaN,6,0101000000E9EDCF4543424040C7D45DD905774140
9520,NaN,0,2019-09-01 02:58:24,32.517109,34.930060,357,0,5,5,ACCIDENT,,1ceab99c-e549-39ff-b1b3-f8bfefb5cc8f,4 צפון,6,0101000000CFBBB1A030424040ACA8C1340C774140
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157822,NaN,0,2019-09-01 22:17:39,32.406866,34.976712,256,0,5,5,ACCIDENT,,5dc9b1d1-541b-3457-b4c7-ea3df0bb7b90,9 מערב,6,01010000005BED612F143440402DCE18E6047D4140
158452,NaN,0,2019-09-01 22:17:39,32.406866,34.976712,256,0,5,6,ACCIDENT,,5dc9b1d1-541b-3457-b4c7-ea3df0bb7b90,9 מערב,6,01010000005BED612F143440402DCE18E6047D4140
159315,NaN,0,2019-09-01 22:45:44,32.325200,35.011889,347,0,1,5,ACCIDENT,ACCIDENT_MAJOR,defd7681-4931-36ca-8e5f-32d8584574e9,6 צפון,3,010100000061545227A02940405017299485814140
160171,NaN,0,2019-09-01 22:45:44,32.325200,35.011889,347,0,1,6,ACCIDENT,ACCIDENT_MAJOR,defd7681-4931-36ca-8e5f-32d8584574e9,6 צפון,3,010100000061545227A02940405017299485814140
162125,NaN,0,2019-09-01 23:32:45,31.801587,35.449841,85,0,5,5,ACCIDENT,ACCIDENT_MAJOR,33f35935-8319-3d64-9939-ab7a9f52ee43,1,6,010100000015E63DCE34CD3F4031B3CF6394B94140

In [36]:
accidents_from_01_09_2019['street'].unique()

array(['1 מערב', '6 דרום', 'NaN', '4 צפון', '1 מזרח', 'דרך הטרמינל',
       '754', '4613', '60 דרום', '40 דרום', '3 מערב', '444',
       '20 איילון דרום', "שד' עמק איילון", "זאב ז'בוטינסקי", 'אברהם יפה',
       '40 צפון', '4 דרום', "ל-רח' לה גוורדייה", 'חיים ויצמן',
       'קיבוץ גלויות', 'הירדן', 'בן גוריון', "ז'בוטינסקי", 'יגאל ידין',
       '653', 'יהודה מרגוזה', 'דרך העצמאות', 'הגדוד ה-21', '505', '574',
       'אלכינא الكينا', 'ל-רמת אפעל, בית-חולים שיבא', '60 צפון',
       'ל-1 מעלה אדומים, הר הצופים', 'בת הרים',
       'ל-431 ירושלים, 42 רחובות, יבנה', '437', '20 איילון צפון',
       'חזקיהו המלך', 'בית וגן', '90', "50 שד' בגין צפון", '5 מערב',
       'ברזילאי יוסף', 'ל-ההלכה', "שד' אהרון קציר", '71',
       'ל-תל אביב, רמת אפעל', 'התדהר', 'חטיבת כפיר', 'יצחק רבין',
       'דרך ירושלים', 'אז"ר', 'אגודת הספורט הפועל', '55', '781', '3855',
       '444 דרום', 'נטף', '2 דרום', 'ל- רמת גן, גבעתיים, תל אביב-יפו',
       'ל-5 תל אביב', 'רוטשילד', 'אוסקר שינדלר', "שד' החשמונאים",
       'יעקב פת', 'האורגים', '40', '6 צפון', 'סוקולוב', '38 צפון',
       '67 מערב', 'המחתרת', 'דרך שיבא', 'פלימן משה', 'דרך השלום',
       'מניה שוחט', 'הרב מוהליבר', 'הרב אהרונסון', '60', 'טרומפלדור',
       '784', '57 מערב', 'הרב שפירא', 'שדרות יצחק רבין', 'יצחק בן צבי',
       'שדרות ירושלים', 'פנחס רוזן', '77 מערב', '44 דרום', '42',
       'שדרות רימון', 'קלישר', 'הפלמ"ח', 'דרך יפו', 'כביש אילת ישן 1954',
       'קובלסקי', 'לילינבלום', 'האסיף', 'רבי עקיבא', '22 צפון', '65 מזרח',
       'הצבי', '9 מזרח', '12', 'רשב"י', 'ל- גבעת רם, מרכז העיר',
       'דבורה הנביאה', 'דוד בנבנישתי', 'ל-4 תל אביב', "שד' דב יוסף",
       'הרוגע', 'شارع عين السلطان', 'הרב משה מלכה', 'צפצפה', 'פינסקר',
       'דרך חברון', 'הזיתים', '5504', '85 מזרח', 'מבצע קדש', 'ויצמן',
       'מנחת יצחק', '461 מערב', '90 צפון', 'הרצל', '65 מערב', 'ביאליק',
       'ארליך דוד', 'יונה הנביא', '66', 'דרך נמיר', '461 מזרח', '85 מערב',
       'פז - צומת קדימה', 'אברהם טביב', '531 מזרח', "שד' שאול המלך",
       'הנביאים', "ל- 50 שד' בגין צפון", '453 מערב', 'ל- הר חוצבים',
       'שיינפיין', '70 דרום', 'אלופי צה"ל', '412', "שד' בני ברית",
       'ל-431 מערב', 'משה דיין', '75 מזרח', '4',
       'מחמוד דרויש محمود درويش', '70 צפון', 'דרך המשחררים', '79',
       'מוצקין', "שד' גולדה מאיר", 'תרצ”ו', 'ל- 70 תל אביב-יפו', 'החיד"א',
       "שד' דוד בן גוריון", 'ההסתדרות', 'השיקמה', 'דרך חיים בר-לב',
       'חנקין', 'הנפח', '75', '25 מערב', 'אלונים', 'טשרניחובסקי',
       'מפרץ שלמה', 'ויליאם אולברייט', '67 מזרח', 'הלח"י',
       "50 שד' בגין דרום", '79 מערב', "שד' מנחם בגין", '77 מזרח',
       'גרוסברד', 'תל חי', 'יעקב זרובבל', '34 דרום', 'אליהו הנביא',
       '5720', 'פרויד', 'ל- 6 דרום', 'צה"ל', '42 דרום', '4303', 'אלקודס',
       "שד' יצחק רבין", 'דרך הבנים', '5815', 'גשר בן דור', 'הרוזמרין',
       'הארגמן', '864', 'משה סנה', 'ירמיהו הנביא', 'דרך אם המושבות',
       'סנעאא', 'מנחם בגין', 'ל-553 אבן יהודה', 'ל-553 נתניה (דרום)',
       'ל- דרך קיבוץ גלויות', 'החרש', '3866', 'קלמן יעקב מן', 'אודם',
       'ישראל פרנקל (העלייה השנייה)', 'מרמורק', "בוסי סנט ג'ורג'", 'יערה',
       '5050', 'אברהם שלונסקי', 'דאהוד סלימאן תלחמי', '444 צפון',
       'ל-4 אשדוד, ירושלים', '652', 'הניצחון', 'הנרייטה סאלד',
       'רחבעם זאבי', '441 מערב חוף הים ראשון לציון', 'האבות', '85',
       'הקבלן', "שד' הרצל", "אלנח'יל", 'דרך הרעות', 'מיצקביץ אדם',
       'אריאל שרון', '35 מזרח', 'יעקב אלעזר', 'דרך בגין',
       'ל-גונן (קטמון), מרכז העיר', '1', '9 מערב'], dtype=object)

In [39]:
accidents_between_00_03 = accidents_from_01_09_2019[is_time_between_00_03]

In [45]:
accidents_between_00_03.head()

,city,confidence,created_at,lontitude,latitude,magvar,number_thumbs_up,report_rating,reliability,alert_type,alert_subtype,uuid,street,road_type,geom
id,,,,,,,,,,,,,,,
3916,NaN,0,2019-09-01 00:55:23,31.836798,34.987609,346,0,5,5,ACCIDENT,,43cf9e73-1d41-3968-9cb4-f220ce31c1d0,1 מערב,3,0101000000B45BCB6438D63F401D1EC2F8697E4140
2699,NaN,0,2019-09-01 00:55:23,31.836798,34.987609,346,0,5,5,ACCIDENT,,43cf9e73-1d41-3968-9cb4-f220ce31c1d0,1 מערב,3,0101000000B45BCB6438D63F401D1EC2F8697E4140
2940,NaN,0,2019-09-01 00:55:23,31.836798,34.987609,346,0,5,5,ACCIDENT,,43cf9e73-1d41-3968-9cb4-f220ce31c1d0,1 מערב,3,0101000000B45BCB6438D63F401D1EC2F8697E4140
3186,NaN,0,2019-09-01 00:55:23,31.836798,34.987609,346,0,5,5,ACCIDENT,,43cf9e73-1d41-3968-9cb4-f220ce31c1d0,1 מערב,3,0101000000B45BCB6438D63F401D1EC2F8697E4140
3430,NaN,0,2019-09-01 00:55:23,31.836798,34.987609,346,0,5,5,ACCIDENT,,43cf9e73-1d41-3968-9cb4-f220ce31c1d0,1 מערב,3,0101000000B45BCB6438D63F401D1EC2F8697E4140

In [41]:
accidents_between_00_03

,city,confidence,created_at,lontitude,latitude,magvar,number_thumbs_up,report_rating,reliability,alert_type,alert_subtype,uuid,street,road_type,geom
id,,,,,,,,,,,,,,,
3916,NaN,0,2019-09-01 00:55:23,31.836798,34.987609,346,0,5,5,ACCIDENT,,43cf9e73-1d41-3968-9cb4-f220ce31c1d0,1 מערב,3,0101000000B45BCB6438D63F401D1EC2F8697E4140
2699,NaN,0,2019-09-01 00:55:23,31.836798,34.987609,346,0,5,5,ACCIDENT,,43cf9e73-1d41-3968-9cb4-f220ce31c1d0,1 מערב,3,0101000000B45BCB6438D63F401D1EC2F8697E4140
2940,NaN,0,2019-09-01 00:55:23,31.836798,34.987609,346,0,5,5,ACCIDENT,,43cf9e73-1d41-3968-9cb4-f220ce31c1d0,1 מערב,3,0101000000B45BCB6438D63F401D1EC2F8697E4140
3186,NaN,0,2019-09-01 00:55:23,31.836798,34.987609,346,0,5,5,ACCIDENT,,43cf9e73-1d41-3968-9cb4-f220ce31c1d0,1 מערב,3,0101000000B45BCB6438D63F401D1EC2F8697E4140
3430,NaN,0,2019-09-01 00:55:23,31.836798,34.987609,346,0,5,5,ACCIDENT,,43cf9e73-1d41-3968-9cb4-f220ce31c1d0,1 מערב,3,0101000000B45BCB6438D63F401D1EC2F8697E4140
3674,NaN,0,2019-09-01 00:55:23,31.836798,34.987609,346,0,5,5,ACCIDENT,,43cf9e73-1d41-3968-9cb4-f220ce31c1d0,1 מערב,3,0101000000B45BCB6438D63F401D1EC2F8697E4140
9216,NaN,1,2019-09-01 02:52:00,32.634163,35.064178,197,0,1,7,ACCIDENT,ACCIDENT_MAJOR,8aa5ceb2-5e33-363b-8638-f1d2876cd52a,6 דרום,3,0101000000A8AAD0402C514040B48F15FC36884140
9545,NaN,2,2019-09-01 02:52:00,32.634163,35.064178,197,0,1,10,ACCIDENT,ACCIDENT_MAJOR,8aa5ceb2-5e33-363b-8638-f1d2876cd52a,6 דרום,3,0101000000A8AAD0402C514040B48F15FC36884140
9516,NaN,0,2019-09-01 02:56:16,32.517678,34.929866,356,0,5,5,ACCIDENT,,8d97e0d9-06ed-3f39-bd25-5df4e3d03a8c,NaN,6,0101000000E9EDCF4543424040C7D45DD905774140
9854,NaN,0,2019-09-01 02:56:16,32.517678,34.929866,356,0,5,5,ACCIDENT,,8d97e0d9-06ed-3f39-bd25-5df4e3d03a8c,NaN,6,0101000000E9EDCF4543424040C7D45DD905774140
10219,NaN,0,2019-09-01 02:56:16,32.517678,34.929866,356,0,5,5,ACCIDENT,,8d97e0d9-06ed-3f39-bd25-5df4e3d03a8c,NaN,6,0101000000E9EDCF4543424040C7D45DD905774140
10618,NaN,0,2019-09-01 02:56:16,32.517678,34.929866,356,0,5,5,ACCIDENT,,8d97e0d9-06ed-3f39-bd25-5df4e3d03a8c,NaN,6,0101000000E9EDCF4543424040C7D45DD905774140
11028,NaN,0,2019-09-01 02:56:16,32.517678,34.929866,356,0,5,5,ACCIDENT,,8d97e0d9-06ed-3f39-bd25-5df4e3d03a8c,NaN,6,0101000000E9EDCF4543424040C7D45DD905774140
11444,NaN,0,2019-09-01 02:56:16,32.517678,34.929866,356,0,5,5,ACCIDENT,,8d97e0d9-06ed-3f39-bd25-5df4e3d03a8c,NaN,6,0101000000E9EDCF4543424040C7D45DD905774140
9520,NaN,0,2019-09-01 02:58:24,32.517109,34.930060,357,0,5,5,ACCIDENT,,1ceab99c-e549-39ff-b1b3-f8bfefb5cc8f,4 צפון,6,0101000000CFBBB1A030424040ACA8C1340C774140
9855,NaN,0,2019-09-01 02:58:24,32.517109,34.930060,357,0,5,5,ACCIDENT,,1ceab99c-e549-39ff-b1b3-f8bfefb5cc8f,4 צפון,6,0101000000CFBBB1A030424040ACA8C1340C774140
10220,NaN,0,2019-09-01 02:58:24,32.517109,34.930060,357,0,5,6,ACCIDENT,,1ceab99c-e549-39ff-b1b3-f8bfefb5cc8f,4 צפון,6,0101000000CFBBB1A030424040ACA8C1340C774140
10619,NaN,0,2019-09-01 02:58:24,32.517109,34.930060,357,0,5,6,ACCIDENT,,1ceab99c-e549-39ff-b1b3-f8bfefb5cc8f,4 צפון,6,0101000000CFBBB1A030424040ACA8C1340C774140
11029,NaN,0,2019-09-01 02:58:24,32.517109,34.930060,357,0,5,6,ACCIDENT,,1ceab99c-e549-39ff-b1b3-f8bfefb5cc8f,4 צפון,6,0101000000CFBBB1A030424040ACA8C1340C774140
11445,NaN,1,2019-09-01 02:58:24,32.517109,34.930060,357,0,5,7,ACCIDENT,,1ceab99c-e549-39ff-b1b3-f8bfefb5cc8f,4 צפון,6,0101000000CFBBB1A030424040ACA8C1340C774140
11896,NaN,1,2019-09-01 02:58:24,32.517109,34.930060,357,0,5,7,ACCIDENT,,1ceab99c-e549-39ff-b1b3-f8bfefb5cc8f,4 צפון,6,0101000000CFBBB1A030424040ACA8C1340C774140
12370,NaN,1,2019-09-01 02:58:24,32.517109,34.930060,357,0,5,8,ACCIDENT,,1ceab99c-e549-39ff-b1b3-f8bfefb5cc8f,4 צפון,6,0101000000CFBBB1A030424040ACA8C1340C774140
12866,NaN,3,2019-09-01 02:58:24,32.517109,34.930060,357,0,5,10,ACCIDENT,,1ceab99c-e549-39ff-b1b3-f8bfefb5cc8f,4 צפון,6,0101000000CFBBB1A030424040ACA8C1340C774140
13388,NaN,4,2019-09-01 02:58:24,32.517109,34.930060,357,0,5,10,ACCIDENT,,1ceab99c-e549-39ff-b1b3-f8bfefb5cc8f,4 צפון,6,0101000000CFBBB1A030424040ACA8C1340C774140
13936,NaN,4,2019-09-01 02:58:24,32.517109,34.930060,357,0,5,10,ACCIDENT,,1ceab99c-e549-39ff-b1b3-f8bfefb5cc8f,4 צפון,6,0101000000CFBBB1A030424040ACA8C1340C774140
14507,NaN,5,2019-09-01 02:58:24,32.517109,34.930060,357,0,5,10,ACCIDENT,,1ceab99c-e549-39ff-b1b3-f8bfefb5cc8f,4 צפון,6,0101000000CFBBB1A030424040ACA8C1340C774140
15107,NaN,5,2019-09-01 02:58:24,32.517109,34.930060,357,0,5,10,ACCIDENT,,1ceab99c-e549-39ff-b1b3-f8bfefb5cc8f,4 צפון,6,0101000000CFBBB1A030424040ACA8C1340C774140
15727,NaN,5,2019-09-01 02:58:24,32.517109,34.930060,357,0,5,10,ACCIDENT,,1ceab99c-e549-39ff-b1b3-f8bfefb5cc8f,4 צפון,6,0101000000CFBBB1A030424040ACA8C1340C774140
16346,NaN,5,2019-09-01 02:58:24,32.517109,34.930060,357,0,5,10,ACCIDENT,,1ceab99c-e549-39ff-b1b3-f8bfefb5cc8f,4 צפון,6,0101000000CFBBB1A030424040ACA8C1340C774140
16973,NaN,5,2019-09-01 02:58:24,32.517109,34.930060,357,0,5,10,ACCIDENT,,1ceab99c-e549-39ff-b1b3-f8bfefb5cc8f,4 צפון,6,0101000000CFBBB1A030424040ACA8C1340C774140
17619,NaN,5,2019-09-01 02:58:24,32.517109,34.930060,357,0,5,10,ACCIDENT,,1ceab99c-e549-39ff-b1b3-f8bfefb5cc8f,4 צפון,6,0101000000CFBBB1A030424040ACA8C1340C774140
18317,NaN,5,2019-09-01 02:58:24,32.517109,34.930060,357,0,5,10,ACCIDENT,,1ceab99c-e549-39ff-b1b3-f8bfefb5cc8f,4 צפון,6,0101000000CFBBB1A030424040ACA8C1340C774140

In [42]:
accidents_between_00_03['street'].unique()

array(['1 מערב', '6 דרום', 'NaN', '4 צפון'], dtype=object)

In [44]:
accidents_between_00_03.loc[9216]

city                                                       NaN
confidence                                                   1
created_at                                 2019-09-01 02:52:00
lontitude                                              32.6342
latitude                                               35.0642
magvar                                                     197
number_thumbs_up                                             0
report_rating                                                1
reliability                                                  7
alert_type                                            ACCIDENT
alert_subtype                                   ACCIDENT_MAJOR
uuid                      8aa5ceb2-5e33-363b-8638-f1d2876cd52a
street                                                  6 דרום
road_type                                                    3
geom                0101000000A8AAD0402C514040B48F15FC36884140
Name: 9216, dtype: object

In [46]:
# accidents from 02.09.2019
date = datetime.date(2019, 9, 2)
is_from_02_09_2019 = df_waze_accidents['created_at'].apply(lambda created_at: created_at.date()) == date

In [48]:
accidents_from_02_09_2019 = df_waze_accidents[is_from_02_09_2019]

In [50]:
accidents_from_02_09_2019.drop_duplicates()

,city,confidence,created_at,lontitude,latitude,magvar,number_thumbs_up,report_rating,reliability,alert_type,alert_subtype,uuid,street,road_type,geom
id,,,,,,,,,,,,,,,
170100,NaN,0,2019-09-02 02:12:41,31.131318,35.003593,306,0,5,5,ACCIDENT,ACCIDENT_MAJOR,da7fcd65-75f6-3eae-b5fc-2ab3749fc809,25 מערב,6,01010000004A60730E9E213F404DBF44BC75804140
170866,NaN,0,2019-09-02 02:23:44,32.841888,35.100987,170,0,5,5,ACCIDENT,ACCIDENT_MINOR,61c259ce-feb5-3c6c-8817-84b88ecff025,22 דרום,3,01010000008A7269FCC26B40401C295B24ED8C4140
171139,NaN,0,2019-09-02 02:23:44,32.841888,35.100987,170,0,5,6,ACCIDENT,ACCIDENT_MINOR,61c259ce-feb5-3c6c-8817-84b88ecff025,22 דרום,3,01010000008A7269FCC26B40401C295B24ED8C4140
171459,NaN,0,2019-09-02 02:37:10,31.130707,35.004181,125,0,5,6,ACCIDENT,ACCIDENT_MAJOR,3955b404-e51f-33c7-87b5-15d20d0dd2b9,25 מזרח,6,0101000000B85B920376213F40DE21C50089804140
171740,NaN,1,2019-09-02 02:37:10,31.130707,35.004181,125,0,5,7,ACCIDENT,ACCIDENT_MAJOR,3955b404-e51f-33c7-87b5-15d20d0dd2b9,25 מזרח,6,0101000000B85B920376213F40DE21C50089804140
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
340974,NaN,1,2019-09-02 21:16:13,31.760445,34.784597,19,0,5,9,ACCIDENT,,6dd085b0-b575-3176-99d6-a18bb8dccba7,"40 צפון, 3 מזרח",6,01010000001F680586ACC23F4015C5ABAC6D644140
341778,NaN,0,2019-09-02 21:39:07,31.776811,34.777901,347,0,1,6,ACCIDENT,ACCIDENT_MINOR,7453f0a6-fdcb-3506-b744-71c631039fae,40 צפון,6,01010000004D2CF015DDC63F404A438D4292634140
345692,NaN,0,2019-09-02 22:23:58,31.603143,34.798428,115,0,5,5,ACCIDENT,,2a1c1910-b7cb-39a2-a966-72420a7199cd,35 מזרח,6,0101000000B3CF6394679A3F40F81A82E332664140
345758,NaN,0,2019-09-02 22:33:30,31.948631,34.957523,294,0,2,5,ACCIDENT,ACCIDENT_MAJOR,e1d97c8b-f620-3ff9-b396-19981d155bb0,NaN,8,0101000000C6F8307BD9F23F407B15191D907A4140
350107,NaN,0,2019-09-02 23:49:08,31.475513,34.775408,164,0,0,6,ACCIDENT,,73c36d08-9d2f-379d-8f7a-9589104d9214,6 דרום,3,0101000000A6D24F38BB793F404487C09140634140

In [51]:
accidents_from_02_09_2019['street'].unique()

array(['25 מערב', '22 דרום', '25 מזרח', 'הרב שפירא', 'NaN', 'ל-דרך השלום',
       '446', 'ל-1 תל אביב-יפו, ירושלים', 'קלמן גבריאלוב', '410 דרך הים',
       '1 מערב', '60', 'ל-481 תל אביב', '5233', 'דרך השבעה', '4 צפון',
       'שירת הים', 'דרך ירוחם צייזל', 'צבי פרנק', 'ל-44 יפו',
       'שדרות בן גוריון', 'דרך זבולון המר', 'מוטה גור',
       "50 שד' בגין צפון", 'הרב בנימין צביאלי', 'סיירת דוכיפת',
       '461 מזרח', '20 איילון צפון', 'ל-1 ירושלים', 'הרב שלום שבזי',
       'טשרניחובסקי', '4 דרום', "שד' רוקח", 'ל-471 חיפה', "שד' הרצל",
       '5 מערב', 'ההסתדרות', '57 מערב', '2 דרום', 'ריינס', 'משה דיין',
       "50 שד' בגין דרום", '471 מערב', '40 צפון', 'הכנסת',
       '20 איילון דרום', 'ל- 3965 מבשרת ציון, מוצא עילית',
       "שד' מנחם בגין", 'מרדכי איש-שלום', "ל- שד' בגין דרום", 'השיקמים',
       '55', '6 דרום', 'אבשלום גיסין', 'אבא הלל', 'רמב"ן',
       'האלוף עוזי נרקיס', 'אבן גבירול', '41 מערב', 'דרך ההגנה',
       'דרך חיים בר-לב', 'דרך מבוא חיפה', '66', '554', 'אליעזר קפלן',
       'אגרון', '44 צפון', 'רמב"ם', 'ל- תל-אביב, אלוף שדה', '6 צפון',
       'דרך בר יהודה', 'משה סנה', '70 דרום', '4', 'שבעת הכוכבים',
       'ל-הרצליה / כביש החוף', "זאב ז'בוטינסקי", '551 מערב', 'דרך נמיר',
       'ל-1 תל אביב ירושלים, 44 יפו', "שד' חיים ויצמן",
       'ל-4 תל אביב, אשדוד', 'ל-471 תל אביב, אשדוד', 'ל- פז',
       'דרך ירושלים', 'ל-הגבעה הצרפתית, הר הצופים, מרכז העיר', '553 מערב',
       'יגאל ידין', 'ל-1 תל אביב ירושלים, 44 יפו רמלה',
       "ל-רח' המסגר ורח' אלנבי", "דה פיצ'וטו", '444', '431 מזרח',
       '42 דרום', '531 מערב', 'רותם', 'יצחק רבין', 'ל-6 דרום, 67 תל אביב',
       'הקוממיות', 'יעקב פת', 'ל-672 דאלית אל-כרמל, אליקים',
       'ל-481 פתח תקווה', 'אלוף שדה',
       "ל- רח' ז'בוטינסקי, דרך נמיר. (מנהרת בגין)", 'הנתיב המהיר',
       '461 מערב', 'הארי טרומן', 'יצחק הנשיא', 'ויצמן', 'יגאל אלון',
       'חניון מרכז הספורט הלאומי', 'מקווה ישראל', 'פנקס', 'בן ציון גָליס',
       'ל- 5 תל אביב', 'דרך אילת', 'הברזל', 'שלבים', 'חיים עוזר',
       '55 מערב', 'כניסה ישנה לקידר', 'מאיר עמית', '89 מערב', 'המוביל',
       '89 מזרח', '65 מערב', 'דוד בן גוריון', 'ביאליק', 'הרצל',
       'ארלוזורוב', "שד' אהרון קציר", 'ל- 4 תל אביב, פתח תקווה',
       'שער ציון', 'אמוראים', 'המרד', 'הרב קוק', 'ל-ההלכה', '754',
       '411 מזרח', '805', 'יוליוס סימון', '65 מזרח',
       'ל-4 חיפה, 1 ירושלים תל אביב', 'דרך העצמאות', 'אליעזר בלבן',
       'מנחם בגין', '38 דרום', 'אייר', 'ל- מרכז העיר', '38 צפון', '5504',
       '411 מערב', 'אליעזר הופיין', '444 צפון', 'ל-1 תל אביב, 4 חיפה',
       'נתנזון', 'דרך יצחק רבין', '23', 'דרך בגין', 'מסדה', 'תמנע',
       'אלנבי', 'כצנלסון', 'שלמה המלך', 'דרך שלמה', 'החליל', '555',
       'הרב עזריאל', 'יצחק אלחנן', 'ל-20 איילון צפון', 'אריה שנקר',
       '444 דרום', '85', "ה' באייר", 'הרמן צבי שפירא', 'דורון',
       "שד' בן גוריון", 'דרך שלמה שמלצר', 'דרך המכבים', '85 מזרח',
       'דרך חיל השריון', '437', 'דרך הים', 'נס לגויים', '53', '2 צפון',
       'עמק התימנים', 'שדרות הציונות', 'הר הזיתים', 'ד"ר בירנבוים',
       'המחשב', 'הערבה', 'אלופי צה"ל', 'ירמיהו', '73', 'הגיבורים',
       '443 מערב', '89', 'אח"י בת גלים', '60 (כביש המנהרות)', 'דיזנגוף',
       'ל-65 עפולה, חדרה', 'המצודה', "שד' יצחק רבין", 'מעגלות הרב פרדס',
       '436', '5 מזרח', 'הירקון', 'החורש', "פרופ' משה שור", '531 מזרח',
       '1 מערב / 6 צפון', 'חנקין', 'השומר', '75', 'הרב משה מלכה', '46',
       '383', 'הרב שאול אבן-דנן', '1 מזרח', 'ל-4 נתניה, חדרה', '25', '79',
       'התל', 'דוד צדוק', '40 דרום', '44 דרום', 'פארן', 'ששת הימים', '38',
       'גיא בן הינום', '446 / 465', 'דוד אלעזר', 'ל-6 דרום', 'מבשרת ציון',
       'שדרות יצחק רבין', 'אריה בן אליעזר', 'המסגר', 'הרב יצחק חי טייב',
       'יהושע בן נון', '60 צפון', 'קלמן יעקב מן', 'י"ד הבנים', 'הנוטע',
       'יחיאל מיכל פינס', 'ל-4 אשדוד', '431 מערב', "שד' דוד בן גוריון",
       'ל- מחלפים אלוף שדה, בר-אילן', 'בן גוריון', '79 מערב', 'לוי אשכול',
       'אחוזה', 'ל-חומת שמואל,גילה', '1 מזרח / 6 דרום', 'אנצו סירני',
       'העליה השניה', "ל- רח' לה גוורדיה, 20 איילון צפון",
       "שד' גולדה מאיר", 'ל-4 ירושלים, אשדוד', 'ירוחם משל', 'קהילת ונציה',
       'הנשיא ויצמן', 'לבונטין', 'הלוחמים', 'דבורנית', '3 מזרח',
       'طريق وادي النار', 'הירמוך', 'שבי ציון', "שד' העצמאות",
       'ל-20 איילון דרום', 'אהרון אייזנברג', 'אלשמס', 'הגלגל', 'דרכי איש',
       '42 צפון', 'קפלן', 'ל-1 ירושלים, תל אביב', 'חטיבת ירושלים',
       'רבי טרפון', '40 צפון, 3 מזרח', '35 מזרח'], dtype=object)

In [52]:
accidents_from_02_09_2019['city'].unique()

array(['NaN', 'בני ברק', 'רחובות', 'חולון', 'מבוא חורון', 'חיפה',
       'ראשון לציון', 'נתניה', 'פתח תקווה', 'מזכרת בתיה', 'ירושלים',
       'ראש העין', 'כפר סבא', 'תל אביב - יפו', 'אשקלון', 'גבעתיים',
       'הוד השרון', 'רמת גן', 'נשר', 'רמת השרון', 'הרצליה', 'עומר',
       'בת ים', 'אשדוד', 'נס ציונה', 'באר שבע', 'אור עקיבא', 'קדימה',
       'רומאנה', 'רעננה', 'מעיליא', 'אזור', 'קריית עקרון', 'קריית אתא',
       'קריית אונו', 'מעלה אדומים', 'טבריה', 'קריית מוצקין',
       'פרדס חנה-כרכור', 'Ramallah - رام الله', 'יקנעם עילית',
       'כפר שמריהו', 'Dura - دورا', 'נצרת עילית', 'כרם מהר"ל',
       'מבשרת ציון', 'מודיעין-מכבים-רעות', 'שדרות', 'זרזיר',
       'Qibya - قبية\u200e', 'מודיעין עילית', 'חדרה',
       'Hebron - الْخَلِيل\u200e', 'כפר יונה', 'نوبا', 'רהט',
       'Bethlehem - بيت لحم', 'Tammun - طمّون', 'ביתר עילית', 'סולם'],
      dtype=object)

In [54]:
accidents_from_02_09_2019.drop_duplicates()['city'].value_counts()

NaN                    959
תל אביב - יפו           87
פתח תקווה               66
ירושלים                 56
חולון                   42
חיפה                    34
בני ברק                 29
רחובות                  26
רמת גן                  22
ראשון לציון             19
בת ים                   14
קריית אתא               14
נס ציונה                13
אשקלון                  11
הרצליה                  11
נתניה                   10
גבעתיים                  9
כפר סבא                  7
נשר                      6
פרדס חנה-כרכור           6
אשדוד                    5
יקנעם עילית              5
רעננה                    5
באר שבע                  4
קריית עקרון              3
אזור                     3
כפר שמריהו               3
ביתר עילית               2
מבשרת ציון               2
אור עקיבא                2
חדרה                     2
טבריה                    2
קריית אונו               2
נצרת עילית               2
Hebron - الْخَلِيل‎      2
מודיעין-מכבים-רעות       2
רומאנה                   1
מעיליא                   1
Qibya - قبية‎            1
Ramallah - رام الله      1
ראש העין                 1
הוד השרון                1
עומר                     1
רהט                      1
שדרות                    1
זרזיר                    1
רמת השרון                1
קדימה                    1
כפר יונה                 1
Dura - دورا              1
קריית מוצקין             1
סולם                     1
כרם מהר"ל                1
نوبا                     1
Bethlehem - بيت لحم      1
Tammun - طمّون           1
מודיעין עילית            1
מעלה אדומים              1
מבוא חורון               1
מזכרת בתיה               1
Name: city, dtype: int64

In [55]:
accidents_from_02_09_2019_no_duplicates = accidents_from_02_09_2019.drop_duplicates()

In [56]:
accidents_from_02_09_2019_tel_aviv = accidents_from_02_09_2019_no_duplicates[accidents_from_02_09_2019_no_duplicates['city'] == 'תל אביב - יפו']

In [57]:
accidents_from_02_09_2019_tel_aviv

,city,confidence,created_at,lontitude,latitude,magvar,number_thumbs_up,report_rating,reliability,alert_type,alert_subtype,uuid,street,road_type,geom
id,,,,,,,,,,,,,,,
189591,תל אביב - יפו,0,2019-09-02 04:49:42,32.102044,34.803071,280,0,5,6,ACCIDENT,,94c038db-6d50-31c4-a2d8-461d77207222,שד' רוקח,2,010100000063601DC70F0D4040DAAED007CB664140
191288,תל אביב - יפו,3,2019-09-02 04:49:42,32.102044,34.803071,280,0,5,10,ACCIDENT,,94c038db-6d50-31c4-a2d8-461d77207222,שד' רוקח,2,010100000063601DC70F0D4040DAAED007CB664140
202900,תל אביב - יפו,0,2019-09-02 05:20:16,32.044809,34.812007,282,0,5,6,ACCIDENT,ACCIDENT_MINOR,da7c774a-9d48-3be2-a40e-73ee1bcffcc7,דרך חיים בר-לב,2,010100000082C8224DBC054040C18F6AD8EF674140
204683,תל אביב - יפו,0,2019-09-02 05:22:37,32.073469,34.782958,93,0,5,6,ACCIDENT,ACCIDENT_MINOR,4747e13b-9179-36bd-9491-d5f2982c1fba,אליעזר קפלן,2,01010000008A22A46E670940401F12BEF737644140
206974,תל אביב - יפו,1,2019-09-02 05:27:29,32.044883,34.811182,102,0,5,7,ACCIDENT,ACCIDENT_MINOR,b2236e8f-2f3c-3744-8c24-99a8e6c344d2,דרך חיים בר-לב,2,0101000000BC92E4B9BE0540404C8DD0CFD4674140
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319840,תל אביב - יפו,1,2019-09-02 17:18:39,32.123446,34.824389,341,0,5,9,ACCIDENT,ACCIDENT_MINOR,1a96e740-b34e-3322-8d16-35ae61fa3816,משה סנה,2,010100000038691A14CD0F40405017299485694140
320401,תל אביב - יפו,1,2019-09-02 17:18:39,32.123446,34.824389,341,0,5,10,ACCIDENT,ACCIDENT_MINOR,1a96e740-b34e-3322-8d16-35ae61fa3816,משה סנה,2,010100000038691A14CD0F40405017299485694140
320943,תל אביב - יפו,2,2019-09-02 17:18:39,32.123446,34.824389,341,0,5,10,ACCIDENT,ACCIDENT_MINOR,1a96e740-b34e-3322-8d16-35ae61fa3816,משה סנה,2,010100000038691A14CD0F40405017299485694140
322832,תל אביב - יפו,0,2019-09-02 17:56:07,32.122828,34.824512,160,0,5,5,ACCIDENT,ACCIDENT_MINOR,0f6ee327-aded-3640-b1ff-6859ddf313bb,משה סנה,2,01010000003C84F1D3B80F40406C94F59B89694140
324106,תל אביב - יפו,0,2019-09-02 17:56:07,32.122828,34.824512,160,0,5,6,ACCIDENT,ACCIDENT_MINOR,0f6ee327-aded-3640-b1ff-6859ddf313bb,משה סנה,2,01010000003C84F1D3B80F40406C94F59B89694140

In [58]:
accidents_from_02_09_2019_tel_aviv['street'].unique()

array(["שד' רוקח", 'דרך חיים בר-לב', 'אליעזר קפלן', 'דרך נמיר',
       'יגאל אלון', 'חניון מרכז הספורט הלאומי', 'פנקס', 'הברזל', 'שלבים',
       'אבן גבירול', 'המרד', 'דרך בגין', 'אלנבי', 'דרך שלמה',
       'דרך חיל השריון', 'נס לגויים', 'דיזנגוף', 'הירקון', 'המסגר',
       'משה סנה', 'ירוחם משל', 'קהילת ונציה'], dtype=object)

In [59]:
accidents_from_02_09_2019_tel_aviv['street'].value_counts()

אבן גבירול                  13
משה סנה                     12
דרך בגין                    10
דרך חיים בר-לב              10
יגאל אלון                    9
שד' רוקח                     4
דרך נמיר                     4
פנקס                         3
נס לגויים                    3
ירוחם משל                    2
המרד                         2
הירקון                       2
הברזל                        2
קהילת ונציה                  2
אלנבי                        2
המסגר                        1
אליעזר קפלן                  1
דרך שלמה                     1
חניון מרכז הספורט הלאומי     1
דרך חיל השריון               1
דיזנגוף                      1
שלבים                        1
Name: street, dtype: int64

In [60]:
accidents_from_02_09_2019_Ibn_Gabirol_accidents = accidents_from_02_09_2019_tel_aviv[accidents_from_02_09_2019_tel_aviv['street'] == 'אבן גבירול']

In [61]:
accidents_from_02_09_2019_Ibn_Gabirol_accidents

,city,confidence,created_at,lontitude,latitude,magvar,number_thumbs_up,report_rating,reliability,alert_type,alert_subtype,uuid,street,road_type,geom
id,,,,,,,,,,,,,,,
237706,תל אביב - יפו,0,2019-09-02 08:02:06,32.091393,34.782849,188,0,5,6,ACCIDENT,,aa68ed08-2d19-322a-8e93-78d7f916f545,אבן גבירול,2,0101000000AA0A0DC4B20B4040685A626534644140
237708,תל אביב - יפו,0,2019-09-02 08:05:26,32.091819,34.782930,192,0,5,5,ACCIDENT,ACCIDENT_MINOR,27a34c12-8df2-3ac0-ba0e-ebcb43740214,אבן גבירול,2,0101000000621399B9C00B40405587DC0C37644140
238299,תל אביב - יפו,0,2019-09-02 08:05:26,32.091819,34.782930,192,0,5,6,ACCIDENT,ACCIDENT_MINOR,27a34c12-8df2-3ac0-ba0e-ebcb43740214,אבן גבירול,2,0101000000621399B9C00B40405587DC0C37644140
238888,תל אביב - יפו,0,2019-09-02 08:05:26,32.091819,34.782930,192,0,5,7,ACCIDENT,ACCIDENT_MINOR,27a34c12-8df2-3ac0-ba0e-ebcb43740214,אבן גבירול,2,0101000000621399B9C00B40405587DC0C37644140
240618,תל אביב - יפו,0,2019-09-02 08:05:26,32.091819,34.782930,192,0,5,8,ACCIDENT,ACCIDENT_MINOR,27a34c12-8df2-3ac0-ba0e-ebcb43740214,אבן גבירול,2,0101000000621399B9C00B40405587DC0C37644140
244501,תל אביב - יפו,0,2019-09-02 09:01:09,32.091987,34.782970,192,0,5,5,ACCIDENT,ACCIDENT_MINOR,49057bf4-be49-385c-933c-fdd2926aaf4e,אבן גבירול,2,01010000001E54E23AC60B4040E3DF675C38644140
245591,תל אביב - יפו,1,2019-09-02 09:01:09,32.091987,34.782970,192,0,5,7,ACCIDENT,ACCIDENT_MINOR,49057bf4-be49-385c-933c-fdd2926aaf4e,אבן גבירול,2,01010000001E54E23AC60B4040E3DF675C38644140
247281,תל אביב - יפו,2,2019-09-02 09:01:09,32.091987,34.782970,192,0,5,9,ACCIDENT,ACCIDENT_MINOR,49057bf4-be49-385c-933c-fdd2926aaf4e,אבן גבירול,2,01010000001E54E23AC60B4040E3DF675C38644140
280771,תל אביב - יפו,0,2019-09-02 13:29:07,32.087491,34.782282,10,0,5,6,ACCIDENT,ACCIDENT_MINOR,3c2dfebd-f514-3cd8-b076-0ca65fd91b5f,אבן גבירול,2,0101000000E0D8B3E7320B4040EF1F0BD121644140
281826,תל אביב - יפו,1,2019-09-02 13:29:07,32.087491,34.782282,10,0,5,9,ACCIDENT,ACCIDENT_MINOR,3c2dfebd-f514-3cd8-b076-0ca65fd91b5f,אבן גבירול,2,0101000000E0D8B3E7320B4040EF1F0BD121644140
282877,תל אביב - יפו,2,2019-09-02 13:29:07,32.087491,34.782282,10,0,5,10,ACCIDENT,ACCIDENT_MINOR,3c2dfebd-f514-3cd8-b076-0ca65fd91b5f,אבן גבירול,2,0101000000E0D8B3E7320B4040EF1F0BD121644140
283913,תל אביב - יפו,0,2019-09-02 13:42:07,32.087290,34.782236,9,0,5,5,ACCIDENT,ACCIDENT_MINOR,a907e582-c63f-3804-a01a-86107026c1ef,אבן גבירול,2,010100000049A297512C0B40407EE02A4F20644140
284945,תל אביב - יפו,0,2019-09-02 13:42:07,32.087290,34.782236,9,0,5,6,ACCIDENT,ACCIDENT_MINOR,a907e582-c63f-3804-a01a-86107026c1ef,אבן גבירול,2,010100000049A297512C0B40407EE02A4F20644140

In [90]:
df_waze_jams = df_waze_alerts[(df_waze_alerts["alert_type"] == 'JAM') & (df_waze_alerts['city'] == 'תל אביב - יפו') & (df_waze_alerts['street'] == 'אבן גבירול') & (df_waze_alerts['created_at'] > '2019-09-02 08:02:06') & (df_waze_alerts['created_at'] < '2019-09-02 12:00:00')]

In [91]:
df_waze_jams

,city,confidence,created_at,lontitude,latitude,magvar,number_thumbs_up,report_rating,reliability,alert_type,alert_subtype,uuid,street,road_type,geom
id,,,,,,,,,,,,,,,
241192,תל אביב - יפו,0,2019-09-02 08:33:28,32.094325,34.783496,187,0,5,5,JAM,JAM_HEAVY_TRAFFIC,fc72f309-1fbd-327d-a713-a3c12794993f,אבן גבירול,2,0101000000FC1873D7120C4040FE45D09849644140
241748,תל אביב - יפו,0,2019-09-02 08:33:28,32.094325,34.783496,187,0,5,5,JAM,JAM_HEAVY_TRAFFIC,fc72f309-1fbd-327d-a713-a3c12794993f,אבן גבירול,2,0101000000FC1873D7120C4040FE45D09849644140
242303,תל אביב - יפו,0,2019-09-02 08:33:28,32.094325,34.783496,187,0,5,5,JAM,JAM_HEAVY_TRAFFIC,fc72f309-1fbd-327d-a713-a3c12794993f,אבן גבירול,2,0101000000FC1873D7120C4040FE45D09849644140
242844,תל אביב - יפו,0,2019-09-02 08:33:28,32.094325,34.783496,187,0,5,5,JAM,JAM_HEAVY_TRAFFIC,fc72f309-1fbd-327d-a713-a3c12794993f,אבן גבירול,2,0101000000FC1873D7120C4040FE45D09849644140
243394,תל אביב - יפו,0,2019-09-02 08:33:28,32.094325,34.783496,187,0,5,5,JAM,JAM_HEAVY_TRAFFIC,fc72f309-1fbd-327d-a713-a3c12794993f,אבן גבירול,2,0101000000FC1873D7120C4040FE45D09849644140
243956,תל אביב - יפו,0,2019-09-02 08:33:28,32.094325,34.783496,187,0,5,5,JAM,JAM_HEAVY_TRAFFIC,fc72f309-1fbd-327d-a713-a3c12794993f,אבן גבירול,2,0101000000FC1873D7120C4040FE45D09849644140
249623,תל אביב - יפו,0,2019-09-02 09:46:24,32.082007,34.781414,0,0,5,5,JAM,JAM_STAND_STILL_TRAFFIC,d64c7741-6769-37b7-9b65-e478ae5d4278,אבן גבירול,2,0101000000838593347F0A40407A51BB5F05644140
250215,תל אביב - יפו,0,2019-09-02 09:46:24,32.082007,34.781414,0,0,5,5,JAM,JAM_STAND_STILL_TRAFFIC,d64c7741-6769-37b7-9b65-e478ae5d4278,אבן גבירול,2,0101000000838593347F0A40407A51BB5F05644140
250803,תל אביב - יפו,0,2019-09-02 09:46:24,32.082007,34.781414,0,0,5,5,JAM,JAM_STAND_STILL_TRAFFIC,d64c7741-6769-37b7-9b65-e478ae5d4278,אבן גבירול,2,0101000000838593347F0A40407A51BB5F05644140
251388,תל אביב - יפו,0,2019-09-02 09:46:24,32.082007,34.781414,0,0,5,5,JAM,JAM_STAND_STILL_TRAFFIC,d64c7741-6769-37b7-9b65-e478ae5d4278,אבן גבירול,2,0101000000838593347F0A40407A51BB5F05644140
251971,תל אביב - יפו,0,2019-09-02 09:46:24,32.082007,34.781414,0,0,5,5,JAM,JAM_STAND_STILL_TRAFFIC,d64c7741-6769-37b7-9b65-e478ae5d4278,אבן גבירול,2,0101000000838593347F0A40407A51BB5F05644140
252535,תל אביב - יפו,0,2019-09-02 09:46:24,32.082007,34.781414,0,0,5,5,JAM,JAM_STAND_STILL_TRAFFIC,d64c7741-6769-37b7-9b65-e478ae5d4278,אבן גבירול,2,0101000000838593347F0A40407A51BB5F05644140